version: '3'

services:
  openldap:
    image: bitnami/openldap
    ports:
      - "1389:1389"
      - "1636:1636"
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
      - LDAP_PORT_NUMBER=389
      - LDAP_LDAPS_PORT_NUMBER=636
    volumes:
      - 'openldap_data:/bitnami/openldap'
    domainname: "example.org"
    hostname: "ldap-server"

volumes:
  openldap_data:
    driver: local
 
